[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install --break-system-packages -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn fmeda_backend.wsgi:application --bind 0.0.0.0:$PORT" 