[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  REACT_APP_API_BASE_URL = "https://your-backend-domain.herokuapp.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_BASE_URL = "https://your-backend-domain.herokuapp.com"

[context.deploy-preview.environment]
  REACT_APP_API_BASE_URL = "https://your-backend-domain.herokuapp.com" 