# Generated by Django 4.2.23 on 2025-07-18 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('failure_rate', models.FloatField(default=0)),
                ('is_safety_related', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lifetime', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_id', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_integrity_level', models.CharField(blank=True, max_length=20)),
                ('RF', models.FloatField(default=0)),
                ('MPFL', models.FloatField(default=0)),
                ('MPFD', models.FloatField(default=0)),
                ('MPHF', models.FloatField(default=0)),
                ('SPFM', models.FloatField(default=0)),
                ('LFM', models.FloatField(default=0)),
                ('safetyrelated', models.FloatField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_functions', to='fmeda.project')),
            ],
            options={
                'unique_together': {('project', 'sf_id')},
            },
        ),
        migrations.CreateModel(
            name='FailureMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('Failure_rate_total', models.FloatField(default=0)),
                ('system_level_effect', models.TextField(blank=True)),
                ('is_SPF', models.BooleanField(default=False)),
                ('is_MPF', models.BooleanField(default=False)),
                ('SPF_safety_mechanism', models.CharField(blank=True, max_length=255)),
                ('MPF_safety_mechanism', models.CharField(blank=True, max_length=255)),
                ('SPF_diagnostic_coverage', models.FloatField(default=0)),
                ('MPF_diagnostic_coverage', models.FloatField(default=0)),
                ('RF', models.FloatField(default=0)),
                ('MPFL', models.FloatField(default=0)),
                ('MPFD', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_modes', to='fmeda.component')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='fmeda.project'),
        ),
        migrations.AddField(
            model_name='component',
            name='related_sfs',
            field=models.ManyToManyField(blank=True, related_name='related_components', to='fmeda.safetyfunction'),
        ),
        migrations.AlterUniqueTogether(
            name='component',
            unique_together={('project', 'comp_id')},
        ),
    ]
